#!/usr/bin/env python3
"""
Argon2H' Reference Implementation for Verification

This implements the Argon2H' algorithm from SPECS.md to generate
test vectors for verifying the CUDA implementation.
"""

import hashlib
import struct

def argon2_hprime(seed: bytes, size: int) -> bytes:
    """
    Argon2H' - Variable-length pseudorandom generator
    
    Algorithm from SPECS.md:
    Function Argon2Hprime(seed, size) =
        output = []
        V0 = Digest(LE32(size) | seed)
        output.append(V0[0..32])
        while output.len() < size
           V[i+1] = Digest(V[i])
           output.append(V[i+1][0..32])
        if output.len() > size
           V[last] = Digest(V[last-1])
           output.append(V[last][0..size - output.len()])
        return output
    """
    if size == 0:
        return b''
    
    output = bytearray()
    
    # V0 = Digest(LE32(size) | seed)
    v_input = struct.pack('<I', size) + seed
    v_current = hashlib.blake2b(v_input, digest_size=64).digest()
    
    # output.append(V0[0..32])
    to_append = min(32, size - len(output))
    output.extend(v_current[:to_append])
    
    # while output.len() < size
    while len(output) < size:
        # V[i+1] = Digest(V[i])
        v_current = hashlib.blake2b(v_current, digest_size=64).digest()
        
        # output.append(V[i+1][0..32])
        to_append = min(32, size - len(output))
        output.extend(v_current[:to_append])
    
    return bytes(output)


def print_test_vector(name: str, seed: bytes, size: int):
    """Generate and print a test vector"""
    result = argon2_hprime(seed, size)
    
    print(f"\n// Test: {name}")
    print(f"// Seed: {seed.hex() if seed else '(empty)'}")
    print(f"// Size: {size} bytes")
    
    # Print as C array
    print(f"const uint8_t expected_{name.lower().replace(' ', '_')}[] = {{")
    
    # Print in rows of 16 bytes
    for i in range(0, len(result), 16):
        chunk = result[i:i+16]
        hex_str = ', '.join(f'0x{b:02x}' for b in chunk)
        if i + 16 < len(result):
            print(f"    {hex_str},")
        else:
            print(f"    {hex_str}")
    
    print("};")
    print(f"// First 64 bytes: {result[:64].hex()}")


if __name__ == '__main__':
    print("// Argon2H' Test Vectors")
    print("// Generated by argon2_verify.py")
    print("// For verifying CUDA implementation")
    
    # Test vectors matching the CUDA tests
    print_test_vector("empty_32", b"", 32)
    print_test_vector("hello_32", b"hello", 32)
    print_test_vector("hello_world_64", b"hello world", 64)
    print_test_vector("abc_64", b"abc", 64)
    print_test_vector("test_33", b"test", 33)
    print_test_vector("test_63", b"test", 63)
    print_test_vector("test_100", b"test", 100)
    print_test_vector("vm_init_256", b"test seed for VM initialization", 256)
    print_test_vector("program_5120", b"program shuffle seed", 5120)
    
    # Additional interesting test cases
    print_test_vector("rom_seed_1024", b"ROM generation seed", 1024)
    
    print("\n// === Quick verification output ===")
    print(f"// empty_32:      {argon2_hprime(b'', 32).hex()}")
    print(f"// hello_32:      {argon2_hprime(b'hello', 32).hex()}")
    print(f"// hello_world_64:{argon2_hprime(b'hello world', 64).hex()}")
    print(f"// abc_64:        {argon2_hprime(b'abc', 64).hex()}")
